#!/usr/bin/env node
// Imports a folder of creature images as a pack under public/creatures/<packId>/ and regenerates
// src/data/image-packs.json plus docs/reports/image-pack-<id>.md. Re-running on the same source
// yields byte-identical output. Files that cannot be matched to a Dex id are reported, never guessed.
//
// Usage:
//   node scripts/images/import-pack.mjs --src <dir> --pack <id> --style <pixel|art> \
//     --author <text> --license <text> [--map <csv>] [--label <text>] [--source <text>] [--max <px>]

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import {
  artPlan,
  bottomAlign,
  buildPackList,
  dexStem,
  mapFiles,
  opaqueBounds,
  parseMapCsv,
  pixelPlan,
  toRanges,
} from "./lib.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
// Tests point this at a temp dir so fixture runs never touch the real pack folders.
const OUT = process.env.IMPORT_PACK_OUT ? path.resolve(process.env.IMPORT_PACK_OUT) : ROOT;
const PACK_ID = /^[a-z0-9][a-z0-9-]{0,31}$/;
const MISSING_LIST_CAP = 60;
const REJECT_LIST_CAP = 60;

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith("--")) throw new Error(`unexpected argument "${a}"`);
    const key = a.slice(2);
    const value = argv[++i];
    if (value === undefined || value.startsWith("--")) throw new Error(`--${key} needs a value`);
    out[key] = value;
  }
  return out;
}

function fail(message) {
  console.error(`[import-pack] ${message}`);
  process.exit(1);
}

async function trimmed(file) {
  const { data, info } = await sharp(file)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const box = opaqueBounds(data, info.width, info.height);
  if (box === null) throw new Error("image is fully transparent");
  const png = await sharp(file).ensureAlpha().extract(box).png().toBuffer();
  return { buffer: png, width: box.width, height: box.height };
}

async function compose(items, style, opts) {
  const side = Math.max(...items.map((i) => Math.max(i.width, i.height)));
  const plan = style === "pixel" ? pixelPlan(side, opts.target) : artPlan(side, opts.max);
  const out = new Map();
  for (const item of items) {
    const w = Math.max(1, Math.round(item.width * plan.scale));
    const h = Math.max(1, Math.round(item.height * plan.scale));
    const resized = await sharp(item.buffer)
      .resize(w, h, { kernel: style === "pixel" ? "nearest" : "lanczos3", fit: "fill" })
      .toBuffer();
    const { left, top } = bottomAlign(plan.canvas, w, h);
    const base = sharp({
      create: {
        width: plan.canvas,
        height: plan.canvas,
        channels: 4,
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      },
    }).composite([{ input: resized, left, top }]);
    const bytes =
      style === "pixel"
        ? await base
            .png({ compressionLevel: 9, adaptiveFiltering: false, palette: false })
            .toBuffer()
        : await base
            .webp({ quality: 82, alphaQuality: 90, effort: 6, smartSubsample: false })
            .toBuffer();
    out.set(item.id, bytes);
  }
  return { canvas: plan.canvas, scale: plan.scale, files: out };
}

function sha(bytes) {
  return createHash("sha256").update(bytes).digest("hex").slice(0, 12);
}

function reportMarkdown({ pack, mapped, missing, unmatched, rejected, scale, srcCount }) {
  const cap = (list, n) => (list.length <= n ? list : list.slice(0, n));
  const lines = [];
  lines.push(`# Image pack ${pack.id}`, "");
  lines.push("Generated by `scripts/images/import-pack.mjs`. Do not hand-edit.", "");
  lines.push("| Field | Value |", "|---|---|");
  lines.push(`| Label | ${pack.label} |`);
  lines.push(`| Style | ${pack.style} |`);
  lines.push(
    `| Canvas | ${pack.width}x${pack.height} ${pack.format} (integer/shared scale ${scale}) |`,
  );
  lines.push(`| Author | ${pack.author} |`);
  lines.push(`| License | ${pack.license} |`);
  lines.push(`| Source | ${pack.source} |`);
  lines.push(`| Source files read | ${srcCount} |`);
  lines.push(`| Covered | ${mapped} of 1025 Dex ids |`);
  lines.push(`| Missing | ${missing.length} |`);
  lines.push(`| Unmatched source files | ${unmatched.length} |`);
  lines.push(`| Rejected | ${rejected.length} |`, "");
  lines.push("## Missing Dex ids", "");
  lines.push(
    missing.length === 0
      ? "None."
      : `${cap(missing, MISSING_LIST_CAP).join(", ")}${missing.length > MISSING_LIST_CAP ? `, and ${missing.length - MISSING_LIST_CAP} more` : ""}`,
    "",
  );
  const byReason = new Map();
  for (const u of unmatched) {
    const arr = byReason.get(u.reason.replace(/\d+/g, "N")) ?? [];
    arr.push(u.file);
    byReason.set(u.reason.replace(/\d+/g, "N"), arr);
  }
  lines.push("## Unmatched source files (never guessed)", "");
  if (unmatched.length === 0) lines.push("None.");
  for (const [reason, files] of [...byReason].sort()) {
    lines.push(
      `- ${files.length} file(s): ${reason}. Examples: ${cap(files, 6).join(", ")}${files.length > 6 ? ", ..." : ""}`,
    );
  }
  lines.push("", "## Rejected", "");
  if (rejected.length === 0) lines.push("None.");
  for (const r of cap(rejected, REJECT_LIST_CAP)) lines.push(`- ${r.file}: ${r.reason}`);
  if (rejected.length > REJECT_LIST_CAP) {
    lines.push(`- and ${rejected.length - REJECT_LIST_CAP} more`);
  }
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  for (const k of ["src", "pack", "style", "author", "license"]) {
    if (!args[k] || args[k].trim() === "") fail(`--${k} is required`);
  }
  if (!PACK_ID.test(args.pack)) fail("--pack must be lowercase letters, digits and dashes");
  if (args.style !== "pixel" && args.style !== "art") fail('--style must be "pixel" or "art"');
  const src = path.resolve(args.src);
  if (!existsSync(src)) fail(`--src ${src} does not exist`);
  const max = args.max === undefined ? 256 : Number(args.max);
  if (!Number.isInteger(max) || max < 32 || max > 512)
    fail("--max must be an integer from 32 to 512");

  const dex = JSON.parse(readFileSync(path.join(ROOT, "src/data/pokedex.json"), "utf8"));
  const csv = args.map ? parseMapCsv(readFileSync(path.resolve(args.map), "utf8")) : new Map();
  const sourceFiles = readdirSync(src, { withFileTypes: true })
    .filter((d) => d.isFile() && !d.name.startsWith("."))
    .map((d) => d.name);

  const { mapped, unmatched, rejected } = mapFiles(sourceFiles, dex, csv);

  const items = [];
  for (const [id, { file }] of mapped) {
    try {
      const t = await trimmed(path.join(src, file));
      items.push({ id, ...t });
    } catch (e) {
      rejected.push({ file, reason: `unreadable: ${e.message}` });
    }
  }
  if (items.length === 0) fail("no usable images after mapping");
  items.sort((a, b) => a.id - b.id);

  const format = args.style === "pixel" ? "png" : "webp";
  const { canvas, scale, files } = await compose(items, args.style, { target: 96, max });

  const outDir = path.join(OUT, "public/creatures", args.pack);
  mkdirSync(outDir, { recursive: true });
  for (const f of readdirSync(outDir)) {
    if (/^\d{4}\.(png|webp)$/.test(f)) rmSync(path.join(outDir, f));
  }
  for (const [id, bytes] of files)
    writeFileSync(path.join(outDir, `${dexStem(id)}.${format}`), bytes);

  const ids = items.map((i) => i.id);
  const pack = {
    id: args.pack,
    label: args.label ?? args.pack,
    style: args.style,
    width: canvas,
    height: canvas,
    format,
    author: args.author.trim(),
    license: args.license.trim(),
    source: args.source ?? path.basename(src),
    coverage: ids.length,
  };
  writeFileSync(path.join(outDir, "pack.json"), `${JSON.stringify(pack, null, 2)}\n`);

  // Regenerate the pack list from every pack.json on disk so it never drifts.
  const creatures = path.join(OUT, "public/creatures");
  const entries = [];
  for (const d of readdirSync(creatures, { withFileTypes: true })) {
    if (!d.isDirectory()) continue;
    const manifest = path.join(creatures, d.name, "pack.json");
    if (!existsSync(manifest)) continue;
    const p = JSON.parse(readFileSync(manifest, "utf8"));
    const packIds = readdirSync(path.join(creatures, d.name))
      .map((f) => new RegExp(`^(\\d{4})\\.${p.format}$`).exec(f))
      .filter((m) => m !== null)
      .map((m) => Number(m[1]));
    entries.push({ pack: p, ids: packIds });
  }
  mkdirSync(path.join(OUT, "src/data"), { recursive: true });
  writeFileSync(
    path.join(OUT, "src/data/image-packs.json"),
    `${JSON.stringify(buildPackList(entries), null, 2)}\n`,
  );

  const dexIds = new Set(dex.map((s) => s.id));
  const missing = [...dexIds].filter((id) => !ids.includes(id)).sort((a, b) => a - b);
  mkdirSync(path.join(OUT, "docs/reports"), { recursive: true });
  writeFileSync(
    path.join(OUT, "docs/reports", `image-pack-${args.pack}.md`),
    reportMarkdown({
      pack,
      mapped: ids.length,
      missing,
      unmatched,
      rejected,
      scale,
      srcCount: sourceFiles.length,
    }),
  );

  const digest = sha(Buffer.from([...files].map(([id, b]) => `${id}:${sha(b)}`).join("\n")));
  console.log(`[import-pack] ${args.pack} (${args.style}) ${canvas}x${canvas} ${format}`);
  console.log(`[import-pack] covered ${ids.length}/${dexIds.size}, missing ${missing.length}`);
  console.log(`[import-pack] unmatched ${unmatched.length}, rejected ${rejected.length}`);
  console.log(`[import-pack] ranges ${JSON.stringify(toRanges(ids))}`);
  console.log(`[import-pack] content digest ${digest}`);
}

main().catch((e) => fail(e.stack ?? String(e)));
