// Writes docs/reports/scouting-distribution.md from src/data/scouting.json. Deterministic.
import { writeFileSync } from "node:fs";
import path from "node:path";
import { SCOUTING } from "@/scouting/scouting-data";
import { ATTRS, ROLES, type Role } from "@/scouting/types";

const N = SCOUTING.length;
const lines: string[] = [];
const push = (...l: string[]) => lines.push(...l);
const fmt = (v: number, d = 2) => v.toFixed(d);
const bar = (n: number, max: number) => "#".repeat(Math.round((n / max) * 40));

push(
  "# Scouting distribution report",
  "",
  `Generated by \`pnpm tsx scripts/data/scouting-report.ts\` from \`src/data/scouting.json\` (${N} species). Every number below is measured from that artifact.`,
  "",
);

push(
  "## Fit per role",
  "",
  "| Role | min | p10 | median | p90 | max | mean |",
  "|---|---|---|---|---|---|---|",
);
const quant = (sorted: number[], q: number) =>
  sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))]!;
for (const r of ROLES) {
  const v = SCOUTING.map((s) => s.fits[r]).sort((a, b) => a - b);
  const mean = v.reduce((a, b) => a + b, 0) / v.length;
  push(
    `| ${r} | ${v[0]} | ${quant(v, 0.1)} | ${quant(v, 0.5)} | ${quant(v, 0.9)} | ${v.at(-1)} | ${fmt(mean, 1)} |`,
  );
}
push("");

push(
  "## Histograms per role",
  "",
  "Bins of 10 fit points. Each `#` is scaled to the largest bin in that role.",
  "",
);
for (const r of ROLES) {
  const bins = new Array(10).fill(0) as number[];
  for (const s of SCOUTING) bins[Math.min(9, Math.floor(s.fits[r] / 10))]!++;
  const max = Math.max(...bins);
  push(`### ${r}`, "", "```text");
  bins.forEach((n, i) => {
    const label = `${String(i * 10).padStart(2)}-${i === 9 ? "100" : String(i * 10 + 9).padStart(2)}`;
    push(`${label.padEnd(7)} ${String(n).padStart(4)} ${bar(n, max)}`);
  });
  push("```", "");
}

push("## Top 10 per role", "");
const top = (r: Role) =>
  [...SCOUTING]
    .sort((a, b) => b.fits[r] - a.fits[r] || a.id - b.id)
    .slice(0, 10)
    .map((s) => `${s.name} ${s.fits[r]}`)
    .join(", ");
for (const r of ROLES) push(`- **${r}.** ${top(r)}`);
push("");

push(
  "## Layer 2 adjustment magnitude per generation",
  "",
  "Per species: count of adjusted attributes and the sum of absolute adjustments. Per adjustment: mean absolute size and net sign.",
  "",
  "| Gen | species | zero-adj share | mean adj count | mean sum abs per species | mean abs per adjustment | net mean per adjustment | share of adjustments >= 8 |",
  "|---|---|---|---|---|---|---|---|",
);
for (let g = 1; g <= 9; g++) {
  const rows = SCOUTING.filter((s) => s.gen === g);
  const adjs = rows.flatMap((s) => Object.values(s.adjustments) as number[]);
  const zero = rows.filter((s) => Object.keys(s.adjustments).length === 0).length;
  const sumAbs = rows.map((s) =>
    (Object.values(s.adjustments) as number[]).reduce((a, b) => a + Math.abs(b), 0),
  );
  const meanSum = sumAbs.reduce((a, b) => a + b, 0) / rows.length;
  const meanAbs = adjs.length ? adjs.reduce((a, b) => a + Math.abs(b), 0) / adjs.length : 0;
  const net = adjs.length ? adjs.reduce((a, b) => a + b, 0) / adjs.length : 0;
  const big = adjs.length ? adjs.filter((v) => Math.abs(v) >= 8).length / adjs.length : 0;
  push(
    `| ${g} | ${rows.length} | ${fmt(zero / rows.length)} | ${fmt(adjs.length / rows.length)} | ${fmt(meanSum)} | ${fmt(meanAbs)} | ${fmt(net)} | ${fmt(big)} |`,
  );
}
push("");

push(
  "## Adjustment histogram per generation",
  "",
  "Absolute adjustment size buckets, count of adjustments.",
  "",
);
push("| Gen | 1-3 | 4-7 | 8-12 |", "|---|---|---|---|");
for (let g = 1; g <= 9; g++) {
  const adjs = SCOUTING.filter((s) => s.gen === g).flatMap((s) =>
    (Object.values(s.adjustments) as number[]).map(Math.abs),
  );
  push(
    `| ${g} | ${adjs.filter((v) => v <= 3).length} | ${adjs.filter((v) => v >= 4 && v <= 7).length} | ${adjs.filter((v) => v >= 8).length} |`,
  );
}
push("");

push(
  "## Adjustments by attribute",
  "",
  "| Attr | adjustments | mean | min | max |",
  "|---|---|---|---|---|",
);
for (const a of ATTRS) {
  const v = SCOUTING.map((s) => s.adjustments[a]).filter((x): x is number => x !== undefined);
  if (v.length === 0) {
    push(`| ${a} | 0 | n/a | n/a | n/a |`);
    continue;
  }
  push(
    `| ${a} | ${v.length} | ${fmt(v.reduce((x, y) => x + y, 0) / v.length)} | ${Math.min(...v)} | ${Math.max(...v)} |`,
  );
}
push("");

push("## Natural role counts (review bestRoles[0])", "", "| Role | species |", "|---|---|");
for (const r of ROLES) push(`| ${r} | ${SCOUTING.filter((s) => s.bestRoles[0] === r).length} |`);
push("");

const out = path.resolve(import.meta.dirname, "../../docs/reports/scouting-distribution.md");
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${path.relative(process.cwd(), out)}`);
