// Closed vocabulary for Layer 2 strengths and weaknesses. A tag names a domain of play.
// In `strengths` it means the species is good at it; in `weaknesses`, poor at it.
export const TAGS = [
  "pace",
  "acceleration",
  "agility",
  "finishing",
  "shot-power",
  "long-shots",
  "kicking-technique",
  "passing",
  "vision",
  "dribbling",
  "close-control",
  "footwork",
  "tackling",
  "marking",
  "positioning",
  "aerial",
  "heading",
  "strength",
  "size",
  "balance",
  "stamina",
  "work-rate",
  "composure",
  "aggression",
  "discipline",
  "teamwork",
  "reach",
  "handling",
  "shot-stopping",
  "reflexes",
  "distribution",
  "durability",
  "flight",
  "intimidation",
  "unpredictability",
  "limb-reach",
] as const;

export type Tag = (typeof TAGS)[number];
