// Literal tokens issued by engine-1. Never regenerate them from the live engine: they stand for
// links already shared, and must replay through the retained bundle exactly as they did.

// Dispatch 2 goldens (src/engine/__tests__/goldens.test.ts at 90fa976).
export const GOLDEN_CUP8_V1 =
  "pd1.W1siYyIsIjQtMi0zLTEiLCIxMjM0NTY3ODkiLCJjIiwicyJdLCJnb2xkZW4tY3VwOCIsW1siciIsInQiXSxbInAiLDg0OSwiczAiXSxbInAiLDMxNSwiczEiXSxbInAiLDI3MiwiczIiXSxbInAiLDY5MSwiczMiXSxbInAiLDQ1MywiczQiXSxbInAiLDc1NCwiczUiXSxbInIiLCJyIl0sWyJwIiw3ODUsInM2Il0sWyJwIiwxNzUsInM3Il0sWyJwIiw2NjMsInM4Il0sWyJwIiwxODgsInM5Il0sWyJwIiw4MDcsInMxMCJdLFsicCIsNzg0LCJiMCJdLFsicCIsNzAzLCJiMSJdLFsicCIsOTQyLCJiMiJdLFsicCIsMTQ1LCJiMyJdLFsicCIsODg0LCJiNCJdXV0";
export const GOLDEN_KANTO151_V1 =
  "pd1.W1siayIsIjMtNS0yIiwicCJdLCJnb2xkZW4ta2FudG8xNTEiLFtbImMiLCJzMCJdLFsicCIsMTQ5LCJzMCJdLFsiYyIsInMxIl0sWyJyIiwicyJdLFsicCIsNzMsInMxIl0sWyJjIiwiczIiXSxbInAiLDY5LCJzMiJdLFsiYyIsInMzIl0sWyJwIiw1MywiczMiXSxbImMiLCJzNCJdLFsicCIsNzgsInM0Il0sWyJjIiwiczUiXSxbInIiLCJzIl0sWyJwIiwxMTYsInM1Il0sWyJjIiwiczYiXSxbInAiLDM3LCJzNiJdLFsiYyIsInM3Il0sWyJwIiw3MSwiczciXSxbImMiLCJzOCJdLFsicCIsMTM0LCJzOCJdLFsiYyIsInM5Il0sWyJyIiwicyJdLFsicCIsMSwiczkiXSxbImMiLCJzMTAiXSxbInAiLDExNywiczEwIl0sWyJjIiwiYjAiXSxbInAiLDksImIwIl0sWyJjIiwiYjEiXSxbInAiLDIyLCJiMSJdLFsiYyIsImIyIl0sWyJyIiwicyJdLFsicCIsMTUsImIyIl0sWyJjIiwiYjMiXSxbInAiLDEyNiwiYjMiXSxbImMiLCJiNCJdLFsicCIsNzcsImI0Il1dXQ";

// The real shared-run link the dispatch 5 accessibility spec opens (e2e/a11y.spec.ts at 90fa976).
export const A11Y_RUN_V1 =
  "pd1.W1siYyIsIjQtMy0zIiwiMTIzNDU2Nzg5IiwibyIsInMiXSwic2VlZC05IixbWyJwIiw2MzAsInMwIl0sWyJwIiw4OTMsInMxIl0sWyJwIiw1NTgsInMyIl0sWyJwIiw2ODEsInMzIl0sWyJwIiw2NTIsInM0Il0sWyJwIiw0NjgsInM1Il0sWyJwIiwyMzMsInM2Il0sWyJwIiw3MTcsInM3Il0sWyJwIiw1NzMsInM4Il0sWyJwIiw2NjMsInM5Il0sWyJwIiw2OTcsInMxMCJdLFsicCIsMjAwLCJiMCJdLFsicCIsNDQ1LCJiMSJdLFsicCIsMjU3LCJiMiJdLFsicCIsNzI0LCJiMyJdLFsicCIsODY2LCJiNCJdXV0";
